### PR TITLE
Improve handling of RPC servers

### LINKED ISSUE #44: port conflicts when using joblib.Parallel or multiprocessing
When I tried to launch several jubatus servers using joblib.Parallel, 
jubakit sometimes get ports that already got by joblib.Parallel and job stopped.

For example, the problem occurs when using scikit-learn.grid.GridSearchCV with parallel settings.
https://gist.github.com/shiodat/57d74827dbffd726a814cc280196c5be

### PR DESCRIPTION
**Pull request by kmaehashi**
This PR improves handling of RPC servers.
Fixes #44 and #48.

* Previously destructor of Service classes call ``_ServiceBackend.stop()`` to stop the server.
  However this behaves unstably when exception is raised (like KeyboardInterrupt triggerd by Ctrl-C).
  I changed it to just destruct the _ServiceBackend instance (this helps CPython VM to trigger destructor as fast as possible), and let destructor of _ServiceBackend class to do the rest.
* TCP port number will now be picked randomly from [10000,30000], instead of sequential assignment.
  We also added retry mechanism (10 times at max) to remedy race conditions.
* Removed global port-to-PID mapping management.
  This was mainly intended for OS X that does not support getting free TCP numbers.
  However it is no longer needed because port number is now randomly assigned and automatically retried if the port is in use.

### CODE REVIEW

**Comment by shiodat** [comment]
LGTM :+1: 
It works correctly using Linux and OS X.

**Comment by shiodat** [comment]
This PR comflicts because `develop` branch is updated by other PRs.
Please merge `develop` branch and recommit.

**Comment by kmaehashi** [comment]
@shiodat Thanks for review! Rebased to the latest develop branch.

**Comment by shiodat** [comment]
@kmaehashi Thanks! :+1:

**Comment by kmaehashi** [comment]
During the conflict fix (rebase), I mistakenly reverted the fix introduced by #35.  I fix this issue directly via e36ae0a4ea6a7e310f05069f9568fc6d7535e53a.

**Pull request merged**
