### PR TITLE
Add jubakit.model example

### PR DESCRIPTION
**Pull request by kmaehashi**

### CODE REVIEW

**Comment by shiodat** [comment]
@kmaehashi Good example 👍 

This example requires a model file as a command-line argument, test failed.
We have to modify the test script, `run_example.py`

I have two ideas.
(1) blacklist this example.
(2) run this example after generating classifier model by `weight_shogun.py`.

**Comment by kmaehashi** [comment]
In the offline discussion, we decided to add model file to the repository.

**Comment by kmaehashi** [comment]
Added model file.

**Comment by shiodat** [comment]
:+1: LGTM

**Pull request merged**
