### PR TITLE
fix to work on OS X El Capitan or later (fix #32)

### LINKED ISSUE #32: Fix to work on OS X (El Capitan or later)
Due to https://github.com/jubatus/jubatus/pull/892, jubakit cannot be used on macOS (>= El Capitan) **on non-standard installation path** (added on 2016-08-24).  In the meantime I want to add workaround code.
I'm thinking of defining `DYLD_LIBRARY_PATH` before executing Jubatus server process based on PATH.

### PR DESCRIPTION
**Pull request by kmaehashi**
Fix #32.

### CODE REVIEW

**Comment by shiodat** [comment]
In case homebrew is installed with default path '/usr/local/', this workaround does not works.
```
~/jubatus/review/jubakit/example (osx-workaround ✔) ᐅ python classifier_bulk.py
Schema: {'types': {'Species': 'l'}, 'fallback_type': 'n', 'keys': {'Species': 'Species'}}
[jubakit] 2016-08-15 18:14:30,955: (INFO) loading all records from loader <jubakit.loader.csv.CSVLoader object at 0x1046e60f0>
[jubakit] 2016-08-15 18:14:30,956: (INFO) records loaded (150 entries)
[jubakit] 2016-08-15 18:14:30,966: (INFO) setting DYLD_LIBRARY_PATH to /usr/local/lib
Traceback (most recent call last):
  File "classifier_bulk.py", line 47, in <module>
    sklearn.metrics.classification_report
  File "/Users/shioda/.pyenv/versions/3.5.1/lib/python3.5/site-packages/jubakit-0.2.2-py3.5.egg/jubakit/classifier.py", line 148, in train_and_classify
  File "/Users/shioda/.pyenv/versions/3.5.1/lib/python3.5/site-packages/jubakit-0.2.2-py3.5.egg/jubakit/base.py", line 449, in run
  File "/Users/shioda/.pyenv/versions/3.5.1/lib/python3.5/site-packages/jubakit-0.2.2-py3.5.egg/jubakit/base.py", line 520, in __init__
  File "/Users/shioda/.pyenv/versions/3.5.1/lib/python3.5/site-packages/jubakit-0.2.2-py3.5.egg/jubakit/base.py", line 686, in _check_installed
RuntimeError: jubaclassifier exit with status -5; confirm that (DY)LD_LIBRARY_PATH is properly set: b'dyld: Symbol not found: __cg_jpeg_resync_to_restart\n  Referenced from: /System/Library/Frameworks/ImageIO.framework/Versions/A/ImageIO\n  Expected in: /usr/local/lib/libJPEG.dylib\n in /System/Library/Frameworks/ImageIO.framework/Versions/A/ImageIO\n'
```

Adding `DYLD_LIBRARY_PATH` , the priority `libJPEG` installed using homebrew becomes higher than system default `libJPEG`, and  jubaclassifier cannot be launched.

**Comment by shiodat** [comment]
* In case homebrew is installed at standard path `/usr/local`, we don't have to set `DYLD_LIBRARY_PATH`.

* In case homebrew is installed at non-standard path,
  * if `libJPEG` / `libPNG` do not be installed,  we have to `DYLD_LIBRARY_PATH` and then jubaclassifier and jubakit works.
  * if `libJPEG` / `libPNG` are already installed, we cannot launch jubaclassifier. This is not jubakit issue but jubatus issue.

**Comment by kmaehashi** [comment]
@shiodat Thank you for review.  I fixed to make this PR work on both standard and non-standard Homebrew installations.

OS X dynamic linker searches libraries in the following order:

* Paths set in ``DYLD_LIBRARY_PATH``; no default value
* ``install_name``; embedded into each program at build time
* Paths set in ``DYLD_FALLBACK_LIBRARY_PATH``; defualt value: ``$(HOME)/lib:/usr/local/lib:/lib:/usr/lib`` (c.f., ``man 1 dyld``)

However, due to a bug of waf (https://github.com/jubatus/homebrew-jubatus/issues/15), ``install_name`` of jubatus built on OS X is broken.  You can see that in this way:

```
% otool -L /opt/homebrew/bin/jubaclassifier
/opt/homebrew/bin/jubaclassifier:
	/private/tmp/jubatus-20160627-74845-1r3tpqb/jubatus-0.9.2/build/jubatus/server/framework/libjubaserv_framework.dylib (compatibility version 0.0.0, current version 0.0.0)
	/private/tmp/jubatus-20160627-74845-1r3tpqb/jubatus-0.9.2/build/jubatus/server/framework/mixer/libjubaserv_mixer.dylib (compatibility version 0.0.0, current version 0.0.0)
	/private/tmp/jubatus-20160627-74845-1r3tpqb/jubatus-0.9.2/build/jubatus/server/common/logger/libjubaserv_common_logger.dylib (compatibility version 0.0.0, current version 0.0.0)
	/private/tmp/jubatus-20160627-74845-1r3tpqb/jubatus-0.9.2/build/jubatus/server/common/libjubaserv_common.dylib (compatibility version 0.0.0, current version 0.0.0)
	/private/tmp/jubatus-20160627-74845-1r3tpqb/jubatus-0.9.2/build/jubatus/server/common/mprpc/libjubaserv_common_mprpc.dylib (compatibility version 0.0.0, current version 0.0.0)
	/private/tmp/jubatus-20160627-74845-1r3tpqb/jubatus-0.9.2/build/jubatus/server/fv_converter/libjubaserv_fv_converter.dylib (compatibility version 0.0.0, current version 0.0.0)
	/opt/homebrew/opt/jubatus-core/lib/libjubatus_core.dylib (compatibility version 0.0.0, current version 0.0.0)
	/opt/homebrew/opt/msgpack059/lib/libmsgpack.3.dylib (compatibility version 4.0.0, current version 4.0.0)
	/opt/homebrew/opt/jubatus-core/lib/libjubatus_util_concurrent.dylib (compatibility version 0.0.0, current version 0.0.0)
	/opt/homebrew/opt/jubatus-core/lib/libjubatus_util_data.dylib (compatibility version 0.0.0, current version 0.0.0)
	/opt/homebrew/opt/jubatus-core/lib/libjubatus_util_lang.dylib (compatibility version 0.0.0, current version 0.0.0)
	/opt/homebrew/opt/jubatus-core/lib/libjubatus_util_math.dylib (compatibility version 0.0.0, current version 0.0.0)
	/opt/homebrew/opt/jubatus-core/lib/libjubatus_util_system.dylib (compatibility version 0.0.0, current version 0.0.0)
	/opt/homebrew/opt/jubatus-core/lib/libjubatus_util_text.dylib (compatibility version 0.0.0, current version 0.0.0)
	/opt/homebrew/opt/jubatus-mpio/lib/libjubatus_mpio.0.dylib (compatibility version 5.0.0, current version 5.3.0)
	/opt/homebrew/opt/log4cxx/lib/liblog4cxx.10.dylib (compatibility version 11.0.0, current version 11.0.0)
	/opt/homebrew/opt/jubatus-msgpack-rpc/lib/libjubatus_msgpack-rpc.0.dylib (compatibility version 5.0.0, current version 5.2.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1226.10.1)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 120.1.0)
```

Paths for some libraries are embedded as ``/private/tmp/...``, which is a path used at build time; aactually it should be ``/opt/homebrew/lib/...``.

**Comment by shiodat** [comment]
Thank you for fixing! LGTM 👍

**Comment by kmaehashi** [comment]
Refs https://github.com/jubatus/jubatus/pull/1181

This workaround code is no longer needed in Jubatus 1.0.2 or later.
Library paths of OS X binaries are now embedded correctly.

```
% otool -L =jubaclassifier
/opt/homebrew/bin/jubaclassifier:
	/opt/homebrew/Cellar/jubatus/1.0.2/lib/libjubaserv_framework.1.dylib (compatibility version 1.0.0, current version 1.0.2)
	/opt/homebrew/Cellar/jubatus/1.0.2/lib/libjubaserv_mixer.1.dylib (compatibility version 1.0.0, current version 1.0.2)
	/opt/homebrew/Cellar/jubatus/1.0.2/lib/libjubaserv_common.1.dylib (compatibility version 1.0.0, current version 1.0.2)
	/opt/homebrew/Cellar/jubatus/1.0.2/lib/libjubaserv_common_mprpc.1.dylib (compatibility version 1.0.0, current version 1.0.2)
	/opt/homebrew/Cellar/jubatus/1.0.2/lib/libjubaserv_common_logger.1.dylib (compatibility version 1.0.0, current version 1.0.2)
	/opt/homebrew/opt/jubatus-core/lib/libjubatus_core.1.dylib (compatibility version 1.0.0, current version 1.0.2)
	/opt/homebrew/opt/msgpack059/lib/libmsgpack.3.dylib (compatibility version 4.0.0, current version 4.0.0)
	/opt/homebrew/opt/jubatus-core/lib/libjubatus_util_concurrent.1.dylib (compatibility version 1.0.0, current version 1.0.2)
	/opt/homebrew/opt/jubatus-core/lib/libjubatus_util_data.1.dylib (compatibility version 1.0.0, current version 1.0.2)
	/opt/homebrew/opt/jubatus-core/lib/libjubatus_util_lang.1.dylib (compatibility version 1.0.0, current version 1.0.2)
	/opt/homebrew/opt/jubatus-core/lib/libjubatus_util_math.1.dylib (compatibility version 1.0.0, current version 1.0.2)
	/opt/homebrew/opt/jubatus-core/lib/libjubatus_util_system.1.dylib (compatibility version 1.0.0, current version 1.0.2)
	/opt/homebrew/opt/jubatus-core/lib/libjubatus_util_text.1.dylib (compatibility version 1.0.0, current version 1.0.2)
	/opt/homebrew/opt/jubatus-mpio/lib/libjubatus_mpio.0.dylib (compatibility version 5.0.0, current version 5.3.0)
	/opt/homebrew/opt/log4cxx/lib/liblog4cxx.10.dylib (compatibility version 11.0.0, current version 11.0.0)
	/opt/homebrew/opt/jubatus-msgpack-rpc/lib/libjubatus_msgpack-rpc.0.dylib (compatibility version 5.0.0, current version 5.2.0)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 120.1.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1226.10.1)
```

**Pull request merged**
