### PR TITLE
speficy library version to support python 2.6

### PR DESCRIPTION
**Pull request by yukimori**
specify numpy and scipy version on extras_requires to support python 2.6.

I think that python 2.6 should be deprecated soon.

### CODE REVIEW

**Comment by kmaehashi** [comment]
I tried this with Python 2.6 and it failed.

```
% pip install '-e.[test]'
DEPRECATION: Python 2.6 is no longer supported by the Python core team, please upgrade your Python. A future version of pip will drop support for Python 2.6
Obtaining file:///home/jubatus/Development/jubakit
Requirement already satisfied: jubatus>=0.8.0 in /home/jubatus/.pyenv/versions/2.6.9/envs/local-2.6.9/lib/python2.6/site-packages (from jubakit==0.5.0)
Requirement already satisfied: psutil in /home/jubatus/.pyenv/versions/2.6.9/envs/local-2.6.9/lib/python2.6/site-packages (from jubakit==0.5.0)
Collecting numpy<=1.11.3 (from jubakit==0.5.0)
  Using cached numpy-1.11.3.zip
Collecting scipy<=0.17.1 (from jubakit==0.5.0)
  Using cached scipy-0.17.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-MSr2xY/scipy/setup.py", line 265, in <module>
        setup_package()
      File "/tmp/pip-build-MSr2xY/scipy/setup.py", line 262, in setup_package
        setup(**metadata)
      File "/home/jubatus/.pyenv/versions/2.6.9/lib/python2.6/distutils/core.py", line 113, in setup
        _setup_distribution = dist = klass(attrs)
      File "/home/jubatus/.pyenv/versions/2.6.9/envs/local-2.6.9/lib/python2.6/site-packages/setuptools/dist.py", line 269, in __init__
        self.fetch_build_eggs(attrs['setup_requires'])
      File "/home/jubatus/.pyenv/versions/2.6.9/envs/local-2.6.9/lib/python2.6/site-packages/setuptools/dist.py", line 313, in fetch_build_eggs
        replace_conflicting=True,
      File "/home/jubatus/.pyenv/versions/2.6.9/envs/local-2.6.9/lib/python2.6/site-packages/pkg_resources/__init__.py", line 826, in resolve
        dist = best[req.key] = env.best_match(req, ws, installer)
      File "/home/jubatus/.pyenv/versions/2.6.9/envs/local-2.6.9/lib/python2.6/site-packages/pkg_resources/__init__.py", line 1092, in best_match
        return self.obtain(req, installer)
      File "/home/jubatus/.pyenv/versions/2.6.9/envs/local-2.6.9/lib/python2.6/site-packages/pkg_resources/__init__.py", line 1104, in obtain
        return installer(requirement)
      File "/home/jubatus/.pyenv/versions/2.6.9/envs/local-2.6.9/lib/python2.6/site-packages/setuptools/dist.py", line 380, in fetch_build_egg
        return cmd.easy_install(req)
      File "/home/jubatus/.pyenv/versions/2.6.9/envs/local-2.6.9/lib/python2.6/site-packages/setuptools/command/easy_install.py", line 640, in easy_install
        return self.install_item(spec, dist.location, tmpdir, deps)
      File "/home/jubatus/.pyenv/versions/2.6.9/envs/local-2.6.9/lib/python2.6/site-packages/setuptools/command/easy_install.py", line 670, in install_item
        dists = self.install_eggs(spec, download, tmpdir)
      File "/home/jubatus/.pyenv/versions/2.6.9/envs/local-2.6.9/lib/python2.6/site-packages/setuptools/command/easy_install.py", line 850, in install_eggs
        return self.build_and_install(setup_script, setup_base)
      File "/home/jubatus/.pyenv/versions/2.6.9/envs/local-2.6.9/lib/python2.6/site-packages/setuptools/command/easy_install.py", line 1078, in build_and_install
        self.run_setup(setup_script, setup_base, args)
      File "/home/jubatus/.pyenv/versions/2.6.9/envs/local-2.6.9/lib/python2.6/site-packages/setuptools/command/easy_install.py", line 1064, in run_setup
        run_setup(setup_script, args)
      File "/home/jubatus/.pyenv/versions/2.6.9/envs/local-2.6.9/lib/python2.6/site-packages/setuptools/sandbox.py", line 246, in run_setup
        raise
      File "/home/jubatus/.pyenv/versions/2.6.9/lib/python2.6/contextlib.py", line 34, in __exit__
        self.gen.throw(type, value, traceback)
      File "/home/jubatus/.pyenv/versions/2.6.9/envs/local-2.6.9/lib/python2.6/site-packages/setuptools/sandbox.py", line 195, in setup_context
        yield
      File "/home/jubatus/.pyenv/versions/2.6.9/lib/python2.6/contextlib.py", line 34, in __exit__
        self.gen.throw(type, value, traceback)
      File "/home/jubatus/.pyenv/versions/2.6.9/envs/local-2.6.9/lib/python2.6/site-packages/setuptools/sandbox.py", line 166, in save_modules
        saved_exc.resume()
      File "/home/jubatus/.pyenv/versions/2.6.9/envs/local-2.6.9/lib/python2.6/site-packages/setuptools/sandbox.py", line 141, in resume
        six.reraise(type, exc, self._tb)
      File "/home/jubatus/.pyenv/versions/2.6.9/envs/local-2.6.9/lib/python2.6/site-packages/setuptools/sandbox.py", line 154, in save_modules
        yield saved
      File "/home/jubatus/.pyenv/versions/2.6.9/envs/local-2.6.9/lib/python2.6/site-packages/setuptools/sandbox.py", line 195, in setup_context
        yield
      File "/home/jubatus/.pyenv/versions/2.6.9/envs/local-2.6.9/lib/python2.6/site-packages/setuptools/sandbox.py", line 243, in run_setup
        DirectorySandbox(setup_dir).run(runner)
      File "/home/jubatus/.pyenv/versions/2.6.9/envs/local-2.6.9/lib/python2.6/site-packages/setuptools/sandbox.py", line 273, in run
        return func()
      File "/home/jubatus/.pyenv/versions/2.6.9/envs/local-2.6.9/lib/python2.6/site-packages/setuptools/sandbox.py", line 242, in runner
        _execfile(setup_script, ns)
      File "/home/jubatus/.pyenv/versions/2.6.9/envs/local-2.6.9/lib/python2.6/site-packages/setuptools/sandbox.py", line 46, in _execfile
        exec(code, globals, locals)
      File "/tmp/easy_install-RZGpUQ/numpy-1.13.0/setup.py", line 34, in <module>
        CLASSIFIERS = """\
    RuntimeError: Python version 2.7 or >= 3.4 required.
```

Maybe scipy 0.16.1 is the last version that supports Python 2.6.
https://pypi.python.org/pypi/scipy/0.16.1
The next version, 0.17.0, does not have wheel for Python 2.6. https://pypi.python.org/pypi/scipy/0.17.0

**Comment by yukimori** [comment]
Thank you for your comment.
I fix scipy version for python 2.6. (0.17.1 -> 0.16.1)

**Comment by kmaehashi** [comment]
:+1: Thanks!

**Comment by kmaehashi** [comment]
Fixes #88

**Pull request merged**
