### PR TITLE
hyper-parameter tuning example using hyperopt library

### PR DESCRIPTION
**Pull request by shiodat**
hyperopt is black-box optimization library and kagglers sometimes use it.
It supports Random Search and Tree of Parzen Estimators (TPE), and this example uses TPE.

hyperopt searches best configuration of classifiers, including linear classifiers and nearest neighbor classifiers.

### CODE REVIEW

**Comment by kmaehashi** [comment]
Hmm I can't get this example to work...


```
$ pip install hyperopt
```

```
$ python classifier_hyperopt_tuning.py
```

```
...
    import bson # -- comes with pymongo
ImportError: No module named bson
```

```
$ pip install pymongo "bson==0.4.3"
```

```
...
    import networkx as nx
ImportError: No module named networkx
```

```
$ pip install networkx
```

```
--------------------------------------------------------------------------------
CANT ENCODE
--------------------------------------------------------------------------------
Traceback (most recent call last):
  File "classifier_hyperopt_tuning.py", line 143, in <module>
    best = fmin(function, space, algo=algo, max_evals=max_evals)
  File "/home/jubatus/.pyenv/versions/local-2.7.11/lib/python2.7/site-packages/hyperopt/fmin.py", line 334, in fmin
    rval.exhaust()
  File "/home/jubatus/.pyenv/versions/local-2.7.11/lib/python2.7/site-packages/hyperopt/fmin.py", line 294, in exhaust
    self.run(self.max_evals - n_done, block_until_done=self.async)
  File "/home/jubatus/.pyenv/versions/local-2.7.11/lib/python2.7/site-packages/hyperopt/fmin.py", line 256, in run
    self.trials.insert_trial_docs(new_trials)
  File "/home/jubatus/.pyenv/versions/local-2.7.11/lib/python2.7/site-packages/hyperopt/base.py", line 405, in insert_trial_docs
    for doc in docs]
  File "/home/jubatus/.pyenv/versions/local-2.7.11/lib/python2.7/site-packages/hyperopt/base.py", line 370, in assert_valid_trial
    bson.BSON.encode(trial)
AttributeError: 'module' object has no attribute 'BSON'
```

Any ideas?

**Comment by kmaehashi** [comment]
* Scripts under `example/` directory are automatically tested by CI: https://github.com/jubatus/jubakit/blob/v0.2.1/tools/run_examples.py.  External module dependencies for examples needs to be listed in `extras_require["test"]`: https://github.com/jubatus/jubakit/blob/v0.2.1/setup.py#L41 so that they are automatically installed before starting the CI test.
* If it is difficult to run this example in CI environment (against all Python versions we support), we should consider blacklisting the example: https://github.com/jubatus/jubakit/blob/v0.2.1/tools/run_examples.py#L23-L24

**Comment by shiodat** [comment]
In python2 environment, Please retry installation without specifying the `bson` version.

```
$ pip install pymongo
$ pip install networkx
$ pip install hyperopt
```

In python3 environment, current `hyperopt` installed using `pip` command does not works.
Using following installation command, you can run this example in python3 environment.

```
$ pip install git+https://github.com/hyperopt/hyperopt.git
```

(Note : `hyperopt-0.0.3.dev` package is not python2 compatible...)

I fixed the installation comments in this example (see d6895b2 commit).

I also fixed the testing script and this example is blacklisted (see 67a9a89 commit) .

**Comment by kmaehashi** [comment]
:+1: Parfait!  Worked both on Python 2.7 & 3.5.1.

```
 score : algo  (hyperparameters)
 0.6667: AROW  (reguralization_weight:0.6667)
 0.9600: NN    (method:minhash, nearest_neighbor_num:84, local_sensitivity:6.9363, hash_num:511)
 0.6667: CW    (reguralization_weight:0.6667)
 0.9200: NN    (method:lsh, nearest_neighbor_num:67, local_sensitivity:6.5082, hash_num:511)
 0.7133: CW    (reguralization_weight:0.7133)
 0.6667: CW    (reguralization_weight:0.6667)
 0.9533: NN    (method:minhash, nearest_neighbor_num:96, local_sensitivity:8.1946, hash_num:511)
 0.3667: AROW  (reguralization_weight:0.3667)
 0.6667: AROW  (reguralization_weight:0.6667)
 0.9533: NN    (method:minhash, nearest_neighbor_num:94, local_sensitivity:0.5122, hash_num:511)
 ------------------------------------------------------------
 best score and hyperparameters
 ------------------------------------------------------------
 0.9600: NN    (method:minhash, nearest_neighbor_num:84, local_sensitivity:6.9363, hash_num:511)
```

**Comment by kmaehashi** [comment]
We forgot to add this to README.  Directly fixed via 8a6ee3d4befd398a96316318eed81ff5e2c31247

**Pull request merged**
