### PR TITLE
Review for initial import

### PR DESCRIPTION
**Pull request by kmaehashi**
This is a proposal of the initial implementation of Jubakit (Jubatus Toolkit), discussed in https://github.com/jubatus/jubatus/issues/1044, that provides simple yet powerful APIs to access techniques often used by analysts when constructing a machine learning model.

Key features:

* Loads dataset from various data sources (like CSV files, RDBs, streams, etc.) to Jubatus with only a few lines of code.
* Integrates with scikit-learn to provide high-level features.  For example:
    * Dataset generators and toy datasets (like iris) provided in sklearn can be used as a input.
    * K-fold cross validation can easily be done.
    * Result from Jubatus can be passed to metrics calculation functions like `classification_report`.
* Jubatus processes can easily be started/stopped from within Python code; users no longer need to manage JSON config files.

Currently Classifier is the only supported service, but more to come!

You can browse through the code in https://github.com/kmaehashi/jubakit/tree/add-code.

### CODE REVIEW

**Comment by kmaehashi** [comment]
@shiodat, @rimms assigned for review.

**Comment by shiodat** [comment]
Jubakit is excellent toolkit!
In importing jubakit officially, I have four comment to improve the usability.

* Unusual writing style in training dataset
In [```example/classifier_parameter.py```]( https://github.com/kmaehashi/jubakit/blob/add-code/example/classifier_parameter.py#L59-L61) L59-L61, the writing style of training looks unusual to me.
	```python
	# Train with the dataset.
	for _ in classifier.train(dataset):
		pass
	```
The following writing style looks common to me.
	```python
	# Train with the dataset.
	classifier.train(dataset)
	```

* Bulk train-test support
Providing bulk train-test method makes it easy to check the performance of jubatus.
For example, following code looks good to me.

	```python
	def fit(method, parameter, train_dataset, test_dataset, metric):
	    """
	    : param method: estimator name
	    : param parameter: parameter for the estimator
	    : param train_dataset: dataset to train
	    : param test_dataset: dataset to test
	    : param metric: scoring metric (e.g. f1_score, accuracy_score, ... etc.)
	    : return: estimation score using test_data
	    """
	    jubatus_config = Config(method=method, parameter=parameter)
	    classifier = Classifier.run(jubatus_config)
	    for _ in classifier.train(train_dataset):
	        pass
	    y_true, y_pred = [], []
	    for (idx, label, result) in classifier.classify(test_dataset):
	        y_true.append(label)
	        y_pred.append(result[0][0])
	    return metric(y_true, y_pred)
	```
What users have to do is only prepare the train-test dataset and call ```fit(...)``` method!

* Python3 support
The implementation only support Python2.
For example, Python3 does not support ```itertools.izip``` method, but ```zip``` in [```jubakit/loader/array.py```](https://github.com/kmaehashi/jubakit/blob/add-code/jubakit/loader/array.py#L5).
For continuous use of jubakit, we should support Python3 in the future.

* Modify README that jubakit only support Linux 
The jubakit examples does not work on my OS X 10.11 El Capitan using Python 2.7.9 (installed by pyenv)
	```sh
	~/jubakit/example ᐅ python classifier_csv.py
	Traceback (most recent call last):
	  File "classifier_csv.py", line 39, in <module>
	    classifier = Classifier.run(cfg)
	  File "build/bdist.macosx-10.11-x86_64/egg/jubakit/base.py", line 306, in run
	  File "build/bdist.macosx-10.11-x86_64/egg/jubakit/base.py", line 363, in __init__
	  File "build/bdist.macosx-10.11-x86_64/egg/jubakit/base.py", line 404, in get_next_free_port
	  File "/Users/shioda/.pyenv/versions/2.7.9/lib/python2.7/site-packages/psutil-4.1.0-py2.7-macosx-10.11-x86_64.egg/psutil/__init__.py", line 1891, in net_connections
	    return _psplatform.net_connections(kind)
	  File "/Users/shioda/.pyenv/versions/2.7.9/lib/python2.7/site-packages/psutil-4.1.0-py2.7-macosx-10.11-x86_64.egg/psutil/_psosx.py", line 170, in net_connections
	    cons = Process(pid).connections(kind)
	  File "/Users/shioda/.pyenv/versions/2.7.9/lib/python2.7/site-packages/psutil-4.1.0-py2.7-macosx-10.11-x86_64.egg/psutil/_psosx.py", line 216, in wrapper
	    raise AccessDenied(self.pid, self._name)
	psutil.AccessDenied: psutil.AccessDenied (pid=48904)
	```

**Comment by kmaehashi** [comment]
@shiodat Thank you for review!

> * Unusual writing style in training dataset

This syntax provides a way to feedback progress of training process to users.
I've added the example code to how to do this: https://github.com/kmaehashi/jubakit/blob/add-code/example/classifier_libsvm.py#L36-L38

cf. [Is using 'yield' a sensible way to report progress of data processing?](http://codereview.stackexchange.com/questions/31789/is-using-yield-a-sensible-way-to-report-progress-of-data-processing)

> * Bulk train-test support

Good!  I've added that method.
https://github.com/kmaehashi/jubakit/blob/add-code/jubakit/classifier.py#L147-L166

As the method name `fit` sounds like doing training only, I changed the method name to `train_and_classify`.
Also, as users may want to customize `converter` section of the config, so the method receives `config` object instead of `method` and `parameter`.

> * Python3 support

Right.  I fixed codes to work with Python 2.7, 3.3, 3.4 and 3.5, and added the requiements to README.
I also added `tox.ini` so that we can tested against multiple Python versions using `tox` command.

> * Modify README that jubakit only support Linux 

I fixed codes to work with OS X.
`jubakit` uses `psutil` package to detect free TCP port number (to assign a LISTEN port for Jubatus server process), however this requires root privilege on OS X.  Now TCP port is statically selected from [10000,30000] on OS X.

----

I added 4 more examples:

* classifier_shogun.py: the most well-known jubatus example code
* classifier_digits.py: using digits dataset from sklearn
* classifier_libsvm.py: using LIBSVM dataset
* classifier_bulk.py: using bulk `train_and_classify` Classifier API

**Comment by shiodat** [comment]
@kmaehashi Thank you for fixing! 

> * Unusual writing style in training dataset

[The libsvm example](https://github.com/kmaehashi/jubakit/blob/add-code/example/classifier_libsvm.py#L36-L38) is good to understand how to use the classify.train(...) method.

> * Bulk train-test support

Thanks for adding the method! 
The method and argument names is easy to understand.

> * Modify README that jubakit only support Linux 

New version of jubakit works correctly on OS X 10.11 El Capitan using Python 2.7.9. 
Thank you for OS X support!

> * Python3 support

Some methods do not work on my Python 3.5 (using anaconda3-2.4.1).

* Integer division problem
In Python3, `n_samples / 2 ` returns float value. I recommend to revise `int(n_samples/2)`.
```python
(anaconda3-2.4.1) ➜  example git:(add-code) python classifier_bulk.py
Traceback (most recent call last):
  File "classifier_bulk.py", line 33, in <module>
    dataset[:n_samples/2],
  File "/home/shioda/.pyenv/versions/anaconda3-2.4.1/lib/python3.5/site-packages/jubakit-0.1.0-py3.5.egg/jubakit/base.py", line 247, in __getitem__
TypeError: slice indices must be integers or None or have an __index__ method
```

*. `json.dump` problem ?
```python
(anaconda3-2.4.1) ➜  example git:(add-code) python classifier_csv.py
Traceback (most recent call last):
  File "classifier_csv.py", line 39, in <module>
    classifier = Classifier.run(cfg)
  File "/home/shioda/.pyenv/versions/anaconda3-2.4.1/lib/python3.5/site-packages/jubakit-0.1.0-py3.5.egg/jubakit/base.py", line 320, in run
  File "/home/shioda/.pyenv/versions/anaconda3-2.4.1/lib/python3.5/site-packages/jubakit-0.1.0-py3.5.egg/jubakit/base.py", line 382, in __init__
  File "/home/shioda/.pyenv/versions/anaconda3-2.4.1/lib/python3.5/json/__init__.py", line 179, in dump
    fp.write(chunk)
  File "/home/shioda/.pyenv/versions/anaconda3-2.4.1/lib/python3.5/tempfile.py", line 483, in func_wrapper
    return func(*args, **kwargs)
TypeError: a bytes-like object is required, not 'str'
```

**Comment by kmaehashi** [comment]
> * Python3 support

I believe that the problem is now fixed.
To avoid these issues to occur again, I added integration tests with Python version matrix to `.travis.yml` and `tox.ini`.

https://travis-ci.org/kmaehashi/jubakit

**Comment by shiodat** [comment]
Nice👍 LGTM!
Thanks for Python3 support.

**Pull request merged**
