### PR TITLE
Implement model transformer

### PR DESCRIPTION
**Pull request by kmaehashi**
This implements feature proposed in #75.

### CODE REVIEW

**Comment by kmaehashi** [comment]
I added tests and docs.

Tests for transformers can be run by:

```
$ python setup.py test --test-suite jubakit.test.integration.test_model
```

**Comment by TkrUdagawa** [comment]
Thanks!
But I ran the tests in Python 3.4.3 and got errors like below:

```
ERROR: test_from_recommender (jubakit.test.integration.test_model.JubaModelTransformationTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/udagawa/work/jubakit/jubakit/jubakit/test/integration/test_model.py", line 78, in test_from_recommender
    self._assertModelLoadable(Recommender, model)
  File "/home/udagawa/work/jubakit/jubakit/jubakit/test/integration/test_model.py", line 42, in _assertModelLoadable
    s.load('test')
  File "/home/udagawa/work/jubakit/jubakit/jubakit/base.py", line 523, in load
    if not self._client().load(name):
  File "/home/udagawa/.pyenv/versions/3.4.3/lib/python3.4/site-packages/jubatus/common/client.py", line 79, in load
    return self.jubatus_client.call("load", [id], TBool(), [TString()])
  File "/home/udagawa/.pyenv/versions/3.4.3/lib/python3.4/site-packages/jubatus/common/client.py", line 38, in call
    ret = future.get()
  File "/home/udagawa/.pyenv/versions/3.4.3/lib/python3.4/site-packages/msgpackrpc/future.py", line 40, in get
    self._error_handler(self._error)
  File "/home/udagawa/.pyenv/versions/3.4.3/lib/python3.4/site-packages/jubatus/common/client.py", line 18, in error_handler
    raise msgpackrpc.error.RPCError(e)
msgpackrpc.error.RPCError: b'server config mismatched: {"converter": {"num_rules": [{"key": "*", "type": "num"}], "string_filter_rules": [], "num_filter_types": {}, "string_types": {"trigram": {"char_num": "3", "method": "ngram"}, "bigram": {"char_num": "2", "method": "ngram"}, "unigram": {"char_num": "1", "method": "ngram"}}, "binary_rules": [], "string_filter_types": {}, "num_filter_rules": [], "string_rules": [{"sample_weight": "tf", "key": "*", "type": "unigram", "global_weight": "idf"}], "binary_types": {}, "num_types": {}}, "parameter": {"parameter": {"threads": -1, "hash_num": 128}, "method": "euclid_lsh"}, "method": "nearest_neighbor_recommender"}, 
expected {"converter": {"num_rules": [{"key": "*", "type": "num"}], "string_filter_rules": [], "num_filter_rules": [], "string_types": {"trigram": {"char_num": "3", "method": "ngram"}, "bigram": {"char_num": "2", "method": "ngram"}, "unigram": {"char_num": "1", "method": "ngram"}}, "binary_rules": [], "string_filter_types": {}, "num_filter_types": {}, "string_rules": [{"sample_weight": "tf", "key": "*", "type": "unigram", "global_weight": "idf"}], "binary_types": {}, "num_types": {}}, "parameter": {"parameter": {"threads": -1, "hash_num": 128}, "method": "euclid_lsh"}, "method": "nearest_neighbor_recommender"}'

```

**Comment by kmaehashi** [comment]
@TkrUdagawa Thanks for review!  This issue should be solved once https://github.com/jubatus/jubatus/pull/1207 got merged.

**Comment by TkrUdagawa** [comment]
Thanks!
I have confirmed that all tests pass using the jubatus patch.
In addition, I tested some transformation and confirmed this function worked correctly.

**Pull request merged**
