### PR TITLE
fix dead links to api pages

### PR DESCRIPTION
**Pull request by shiodat**
fix dead links to api pages

### CODE REVIEW

**Comment by kmaehashi** [comment]
Good catch!  The docs needs to be fixed too... https://raw.githubusercontent.com/jubatus/jubakit/master/doc/source/architecture/service.rst

**Comment by shiodat** [comment]
@kmaehashi Thanks for review! I fix other api links too.

**Comment by rimms** [comment]
👍

**Comment by rimms** [comment]
💯

**Pull request merged**
